apiVersion: v1
kind: LimitRange
metadata:
  name: limits
spec:
  limits:
  - default:
      cpu: 1000m
      memory: 1024Mi
    defaultRequest:
      cpu: 500m
      memory: 512Mi
    type: Container
    
