apiVersion: v1
kind: Pod
metadata:
  name: test-pod-cmd
spec:
  containers:
    - name: test-container
      image: registry.access.redhat.com/rhel7/rhel
      command: ["/bin/sh", "-c", "echo Error Level: $(LOG_LEVEL) - Error Location: $(LOG_LOCTION)" ]
      env:
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: log-config
              key: log.level
        - name: LOG_LOCATION
          valueFrom:
            configMapKeyRef:
              name: log-config
              key: log.location
  restartPolicy: Never
